[workspace]
members = [
    "meilisearch-core",
    "meilisearch-http",
    "meilisearch-schema",
    "meilisearch-types",
]

[profile.release]
debug = true

[patch.crates-io]
pest = { git = "https://github.com/pest-parser/pest.git", rev = "51fd1d49f1041f7839975664ef71fe15c7dcaf67" }
